{
    "language": "node_js",

    "node_js": [
        "stable"
    ],

    "after_success": [
        "npm install -g codeclimate-test-reporter",
        "nyc report --reporter=text-lcov | codeclimate-test-reporter",

        "npm install -g codacy-coverage",
        "nyc report --reporter=text-lcov | codacy-coverage",

        "bash <(curl -s https://codecov.io/bash)"
    ]
}
