{
    "language": "node_js",
    "node_js": [
        "stable"
    ],
    "after_success": [
        "npm install -g codeclimate-test-reporter",
        "nyc report --reporter=text-lcov | codeclimate-test-reporter"
    ]
}
